### ISSUE TITLE
refactor: Migrate to React.js app

### ISSUE THREAD

**Issue by esau-morais** [esau-morais/To-Do#1]
### Actual

HTML, CSS and JavaScript 

### Expected 

React.js

### Guides

1. Fork this repository and clone

![Forking](https://camo.githubusercontent.com/6f03010c651d060f8b7cfc17da7098c1757c4ead/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f666f726b2e706e67)

`git clone github.com/user/To-Do.git`

2. Create a new branch called `migrate-to-react` and publish

`git checkout -b migrate-to-react `

3. Clear the project and initialize React.js app as the root folder

`npx create-react-app to-do`

### Tips

1. Try to make a different design

2. Folder structure does matter

**Comment by EnechukwuChibuike** [comment]
Can I do that?

**Comment by esau-morais** [comment]
Sure, go ahead!

**Comment by jitender24** [comment]
Hey! esau-morais, I can change your project it'll look better, and using react I can add more functionality like edit todos. Currently, in your project, you can't edit the todo I can add this functionality.

**Comment by esau-morais** [comment]
> Hey! esau-morais, I can change your project it'll look better, and using react I can add more functionality like edit todos. Currently, in your project, you can't edit the todo I can add this functionality.

You have to be fast, @EnechukwuChibuike already asked for
